board: [${armanbilge}, ${djspiewak}, ${jducoeur}, ${valencik}]
staff: [${armanbilge}]
coc: [${armanbilge}, ${hkateu}, ${samspills}, ${satabin}, ${valencik}]
security: [${rossabaker}, ${armanbilge}, ${bpholt}, ${antoniojimeneznieto}]

tsc: [
  ${zainabali}
  ${armanbilge}
  ${chingles}
  ${danicheg}
  ${dhinojosa}
  ${lukajcb}
  ${jepfp}
  ${antoniojimeneznieto}
  ${SabrinaXKL}
  ${lenguyenthanh}
  ${iRevive}
  ${samspills}
  ${mpilquist}
  ${igor-ramazanov}
  ${reardonj}
  ${Hombre-x}
  ${djspiewak}
  ${satorg}
  ${jducoeur}
  ${valencik}
  ${Koroeskohr}
]
